In [212]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [213]:
dataset=pd.read_csv('loan_data_set.csv')
dataset

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [214]:
dataset = dataset.dropna()
dataset

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [216]:
gender = {'Male': 1,'Female': 2}
married = {'Yes': 3, 'No': 4}
#dependents = {1: 1, 0: 0, 3+: 3}
education = {'Graduate': 5, 'Not Graduate': 6}
self_employed = {'Yes': 7, 'No': 8}
property_area = {'Semiurban': 9, 'Rural': 10, 'Urban': 11}
loan_status = {'Y': 12, 'N': 13}

dataset.Gender = [gender[item] for item in dataset.Gender]
dataset.Married = [married[item] for item in dataset.Married]
dataset.Education = [education[item] for item in dataset.Education]
dataset.Self_Employed = [self_employed[item] for item in dataset.Self_Employed]
dataset.Property_Area = [property_area[item] for item in dataset.Property_Area]
dataset.Loan_Status = [loan_status[item] for item in dataset.Loan_Status]

print(dataset)

      Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
1    LP001003       1        3          1          5              8
2    LP001005       1        3          0          5              7
3    LP001006       1        3          0          6              8
4    LP001008       1        4          0          5              8
5    LP001011       1        3          2          5              7
..        ...     ...      ...        ...        ...            ...
609  LP002978       2        4          0          5              8
610  LP002979       1        3         3+          5              8
611  LP002983       1        3          1          5              8
612  LP002984       1        3          2          5              8
613  LP002990       2        4          0          5              7

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
1               4583             1508.0       128.0             360.0
2               3000                0.0        66.0             360.0
3               2583             2358.0       120.0             360.0
4               6000                0.0       141.0             360.0
5               5417             4196.0       267.0             360.0
..               ...                ...         ...               ...
609             2900                0.0        71.0             360.0
610             4106                0.0        40.0             180.0
611             8072              240.0       253.0             360.0
612             7583                0.0       187.0             360.0
613             4583                0.0       133.0             360.0

     Credit_History  Property_Area  Loan_Status
1               1.0             10           13
2               1.0             11           12
3               1.0             11           12
4               1.0             11           12
5               1.0             11           12
..              ...            ...          ...
609             1.0             10           12
610             1.0             10           12
611             1.0             11           12
612             1.0             11           12
613             0.0              9           13

[480 rows x 13 columns]

C:\Users\rahul\AppData\Local\Temp\ipykernel_9800\4162577004.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.Gender = [gender[item] for item in dataset.Gender]
C:\Users\rahul\AppData\Local\Temp\ipykernel_9800\4162577004.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.Married = [married[item] for item in dataset.Married]
C:\Users\rahul\AppData\Local\Temp\ipykernel_9800\4162577004.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.Education = [education[item] for item in dataset.Education]
C:\Users\rahul\AppData\Local\Temp\ipykernel_9800\4162577004.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.Self_Employed = [self_employed[item] for item in dataset.Self_Employed]
C:\Users\rahul\AppData\Local\Temp\ipykernel_9800\4162577004.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.Property_Area = [property_area[item] for item in dataset.Property_Area]
C:\Users\rahul\AppData\Local\Temp\ipykernel_9800\4162577004.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.Loan_Status = [loan_status[item] for item in dataset.Loan_Status]

In [217]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder() 
label_encoder.fit(dataset["Dependents"])

dependents = label_encoder.transform(dataset['Dependents'])
dataset['Dependents'] = dependents

C:\Users\rahul\AppData\Local\Temp\ipykernel_9800\2547137562.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Dependents'] = dependents

In [218]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 480 entries, 1 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            480 non-null    object
 1   Gender             480 non-null    int64
 2   Married            480 non-null    int64
 3   Dependents         480 non-null    int32
 4   Education          480 non-null    int64
 5   Self_Employed      480 non-null    int64
 6   ApplicantIncome    480 non-null    int64
 7   CoapplicantIncome  480 non-null    float64
 8   LoanAmount         480 non-null    float64
 9   Loan_Amount_Term   480 non-null    float64
 10  Credit_History     480 non-null    float64
 11  Property_Area      480 non-null    int64
 12  Loan_Status        480 non-null    int64
dtypes: float64(4), int32(1), int64(7), object(1)
memory usage: 50.6+ KB

In [219]:
dataset

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,1,3,1,5,8,4583,1508.0,128.0,360.0,1.0,10,13
2,LP001005,1,3,0,5,7,3000,0.0,66.0,360.0,1.0,11,12
3,LP001006,1,3,0,6,8,2583,2358.0,120.0,360.0,1.0,11,12
4,LP001008,1,4,0,5,8,6000,0.0,141.0,360.0,1.0,11,12
5,LP001011,1,3,2,5,7,5417,4196.0,267.0,360.0,1.0,11,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,2,4,0,5,8,2900,0.0,71.0,360.0,1.0,10,12
610,LP002979,1,3,3,5,8,4106,0.0,40.0,180.0,1.0,10,12
611,LP002983,1,3,1,5,8,8072,240.0,253.0,360.0,1.0,11,12
612,LP002984,1,3,2,5,8,7583,0.0,187.0,360.0,1.0,11,12
613,LP002990,2,4,0,5,7,4583,0.0,133.0,360.0,0.0,9,13

In [220]:
dataset = dataset.drop(['Married'], axis=1)
dataset = dataset.drop(['Dependents'], axis=1)
dataset = dataset.drop(['CoapplicantIncome'], axis=1)
dataset

,Loan_ID,Gender,Education,Self_Employed,ApplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,1,5,8,4583,128.0,360.0,1.0,10,13
2,LP001005,1,5,7,3000,66.0,360.0,1.0,11,12
3,LP001006,1,6,8,2583,120.0,360.0,1.0,11,12
4,LP001008,1,5,8,6000,141.0,360.0,1.0,11,12
5,LP001011,1,5,7,5417,267.0,360.0,1.0,11,12
...,...,...,...,...,...,...,...,...,...,...
609,LP002978,2,5,8,2900,71.0,360.0,1.0,10,12
610,LP002979,1,5,8,4106,40.0,180.0,1.0,10,12
611,LP002983,1,5,8,8072,253.0,360.0,1.0,11,12
612,LP002984,1,5,8,7583,187.0,360.0,1.0,11,12
613,LP002990,2,5,7,4583,133.0,360.0,0.0,9,13

In [221]:
X = dataset.iloc[:, 1:9]
Y = dataset.iloc[:, 9]
print(X)
print(Y)

     Gender  Education  Self_Employed  ApplicantIncome  LoanAmount  \
1         1          5              8             4583       128.0
2         1          5              7             3000        66.0
3         1          6              8             2583       120.0
4         1          5              8             6000       141.0
5         1          5              7             5417       267.0
..      ...        ...            ...              ...         ...
609       2          5              8             2900        71.0
610       1          5              8             4106        40.0
611       1          5              8             8072       253.0
612       1          5              8             7583       187.0
613       2          5              7             4583       133.0

     Loan_Amount_Term  Credit_History  Property_Area
1               360.0             1.0             10
2               360.0             1.0             11
3               360.0             1.0             11
4               360.0             1.0             11
5               360.0             1.0             11
..                ...             ...            ...
609             360.0             1.0             10
610             180.0             1.0             10
611             360.0             1.0             11
612             360.0             1.0             11
613             360.0             0.0              9

[480 rows x 8 columns]
1      13
2      12
3      12
4      12
5      12
       ..
609    12
610    12
611    12
612    12
613    13
Name: Loan_Status, Length: 480, dtype: int64

In [222]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=0)

In [223]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [224]:
from sklearn.linear_model import LogisticRegression
log_classifier = LogisticRegression(random_state=0)
log_classifier.fit(X_train, Y_train)

LogisticRegression(random_state=0)

In [225]:
Y_pred = log_classifier.predict(X_test)
Y_pred

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 12, 12, 12, 12,
       12, 13, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 13, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 13, 13, 13, 12, 12, 13, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 13, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 12,
       12, 13, 12, 12, 13, 12, 13, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 13, 12, 12, 12, 12, 12, 13, 12, 12, 12, 12, 12, 13,
       12], dtype=int64)

In [226]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [227]:
cm

array([[78,  0],
       [27, 15]], dtype=int64)

In [228]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, Y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.775

In [197]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [198]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion='entropy')
classifier.fit(X_train, Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [199]:
Y_pred = classifier.predict(X_test)
Y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1], dtype=int64)

In [200]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)
cm

array([[19, 23],
       [ 8, 70]], dtype=int64)

In [201]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, Y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.7416666666666667

In [202]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, Y_train1, Y_test1 = train_test_split(X, Y, test_size=0.20, random_state=0)

In [203]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train1 = sc.fit_transform(X_train1)
X_test1 = sc.transform(X_test1)

In [204]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion='entropy')
classifier.fit(X_train1, Y_train1)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [205]:
Y_pred1 = classifier.predict(X_test1)
Y_pred1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1], dtype=int64)

In [206]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, Y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.7416666666666667

In [207]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [208]:
Y_pred = classifier.predict(X_test)

In [209]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [210]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, Y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.675

In [211]:
in_gender = input('Gender:')
in_married = input('Enter marrietal status:')
in_dependents = int(input('Dependents:'))
in_education = input('Education:')
in_self_employed = input('Self_Employed:')
in_applicant_income = int(input('Applicant Income:'))
in_coapplicant_income = int(input('Coapplicant Income:'))
in_loan_amount = int(input('Loan Amount:'))
in_loan_amount_term = int(input('Loan Amount Term:'))
in_credit_history = int(input('Credit History'))
in_property_area = input('Property Area:')

KeyboardInterrupt: Interrupted by user

In [ ]:
in_gender = input('Gender:')
in_married = input('Enter marrietal status:')
in_dependents = int(input('Dependents:'))
in_education = input('Education:')
in_self_employed = input('Self_Employed:')
in_applicant_income = int(input('Applicant Income:'))
in_coapplicant_income = int(input('Coapplicant Income:'))
in_loan_amount = int(input('Loan Amount:'))
in_loan_amount_term = int(input('Loan Amount Term:'))
in_credit_history = int(input('Credit History'))
in_property_area = input('Property Area:')

log_Y_predict = log_classifier.predict([[gender[in_gender], married[in_married], in_dependents, education[in_education], self_employed[in_self_employed], in_applicant_income, in_coapplicant_income, in_loan_amount, in_loan_amount_term, in_credit_history, property_area[in_property_area]]])
print("Prediction: ", log_Y_predict)